# These are supported funding model platforms
custom: ['https://www.paypal.me/AkarinLiu']
custon: ['https://github.com/AkarinLiu/AkarinLiu/raw/master/alipay.jpg']
custon: ['https://github.com/AkarinLiu/AkarinLiu/raw/master/wechat.jpg']
